import { component$ } from "@builder.io/qwik";
import Text from "~/components/common/Text/Text";
import type { DocumentHead } from "@builder.io/qwik-city";

export default component$(() => {
  return (
    <section class="container mx-auto max-w-3xl px-8 pt-24 lg:pt-32">
      <Text tag="h1">Privacy Policy</Text>
      <Text>Last updated: March 8, 2023</Text>
      <Text>
        This privacy policy (“Privacy Policy”) describes Our policies and
        procedures on the collection, use and disclosure of Your information
        when You use the Services and tells You about Your privacy rights and
        how the law protects You.
      </Text>
      <Text>
        We are the data controller of Your Personal Data and use Your Personal
        Data to provide and improve the Services. By using the Services, You
        agree to the collection and use of information in accordance with this
        Privacy Policy.
      </Text>
      <Text tag="h2">Interpretation and Definitions</Text>
      <Text tag="h3">Interpretation</Text>
      <Text>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </Text>
      <Text tag="h3">Definitions</Text>
      <Text>For the purposes of this Privacy Policy:</Text>
      <ul class="list-disc mb-8">
        <li>
          <Text noMargin>
            <b>"Company"</b> <b>"We"</b>, <b>"Us"</b> or <b>"Our"</b> refers to
            Untied World AB, Swedish registration number 559400-2304,
            Bråvallagatan 8, 113 36 Stockholm Sweden.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>"Cookies"</b> are small files that are placed on Your computer,
            mobile device or any other device by a website, containing the
            details of Your browsing history on that website among its many
            uses.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>"Device"</b> means any device that can access the Services such
            as a computer, a cellphone or a digital tablet.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>“Personal Data”</b> is any information that relates to an
            identified or identifiable individual.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>“Services”</b> includes our Website and any other services,
            features, content, or applications offered by Untied World AB.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>“Service Provider”</b> means any natural or legal person who
            processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Services, to provide the Services on behalf of the
            Company, to perform services related to the Services or to assist
            the Company in analyzing how the Services are used.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>“Usage Data”</b> refers to data collected automatically, either
            generated by the use of the Services or from the Services&apos;
            infrastructure itself (for example, the number of steps You have
            taken during a day).
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>“Website”</b> refers to Untied, accessible from{" "}
            <a href="https://www.untied.world">https://www.untied.world</a>
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>“You”</b> means the individual accessing or using the Services,
            or the company, or other legal entity on behalf of which such
            individual is accessing or using the Services, as applicable.
          </Text>
        </li>
      </ul>
      <Text tag="h2">Collecting and Using Your Personal Data</Text>
      <Text tag="h3">Types of Data Collected</Text>
      <Text tag="h4">Personal Data</Text>
      <Text>
        While using Our Services, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </Text>
      <ul class="list-disc mb-8">
        <li>
          <Text noMargin>Email address</Text>
        </li>
        <li>
          <Text noMargin>First name and last name</Text>
        </li>
        <li>
          <Text noMargin>Usage Data</Text>
        </li>
        <li>
          <Text noMargin>Health and fitness data</Text>
        </li>
      </ul>
      <Text tag="h4">Usage Data</Text>
      <Text>
        Usage Data is collected automatically when using the Services.
      </Text>
      <Text>
        Usage Data may include information such as Your Device&apos;s Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Services that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </Text>
      <Text>
        When You access the Services by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other
        diagnostic data.
      </Text>
      <Text>
        We may also collect information that Your browser sends whenever You
        visit our Services or when You access the Services by or through a
        mobile device.
      </Text>
      <Text tag="h4">Health and fitness data</Text>
      <Text>
        As part of our Services, we may collect health and health-related
        information that you voluntarily provide through our Services. This
        information is maintained in our systems and may include, but is not
        limited to, API access keys used to record activity and/or general
        health information provided by the devices.
      </Text>
      <Text tag="h4">Tracking Technologies and Cookies</Text>
      <Text>
        We use Cookies and similar tracking technologies to track the activity
        on Our Services and store certain information. Tracking technologies
        used are beacons, tags, and scripts to collect and track information and
        to improve and analyze Our Services. The technologies We use may
        include:
      </Text>
      <ul class="list-disc mb-8">
        <li>
          <Text noMargin>
            <b>Cookies or Browser Cookies.</b> A cookie is a small file placed
            on Your Device. You can instruct Your browser to refuse all Cookies
            or to indicate when a Cookie is being sent. However, if You do not
            accept Cookies, You may not be able to use some parts of our
            Services. Unless you have adjusted Your browser setting so that it
            will refuse Cookies, our Services may use Cookies.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>Web Beacons.</b> Certain sections of our Services and our emails
            may contain small electronic files known as web beacons (also
            referred to as clear gifs, pixel tags, and single-pixel gifs) that
            permit the Company, for example, to count users who have visited
            those pages or opened an email and for other related website
            statistics (for example, recording the popularity of a certain
            section and verifying system and server integrity).
          </Text>
        </li>
      </ul>
      <Text>
        At Untied, we are committed to complying with privacy regulations on our
        website and on our web analytics product too.
      </Text>
      <Text tag="h3">Use of Your Personal Data</Text>
      <Text>
        The Company may process Your Personal Data for the following purposes:
      </Text>
      <ul class="list-disc mb-8">
        <li>
          <Text noMargin>
            <b>To provide and maintain our Services</b>, including to monitor
            the usage of our Services.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>To manage Your requests:</b> To attend and manage Your requests
            to Us.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>For business transfers:</b> We may use Your information to
            evaluate or conduct a merger, divestiture, restructuring,
            reorganization, dissolution, or other sale or transfer of some or
            all of Our assets, whether as a going concern or as part of
            bankruptcy, liquidation, or similar proceeding, in which Personal
            Data held by Us about our Services users is among the assets
            transferred.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>For other purposes:</b> We may use Your information for other
            purposes, such as data analysis, identifying usage trends,
            determining the effectiveness of our promotional campaigns and to
            evaluate and improve our Services, products, marketing and your
            experience.
          </Text>
        </li>
      </ul>
      <Text>We may share Your Personal Data in the following situations:</Text>
      <ul class="list-disc mb-8">
        <li>
          <Text noMargin>
            <b>With Service Providers:</b> We may share Your Personal Data with
            Service Providers to monitor and analyze the use of our Services.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>For business transfers:</b> We may share or transfer Your
            Personal Data in connection with, or during negotiations of, any
            merger, sale of Company assets, financing, or acquisition of all or
            a portion of Our business to another company.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>With business partners:</b> We may share Your information with
            Our business partners to offer You certain products, services or
            promotions.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>With Your consent:</b> We may disclose Your Personal Data for any
            other purpose with Your consent.
          </Text>
        </li>
      </ul>

      <Text tag="h3">Retention of Your Personal Data</Text>
      <Text>
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use Your Personal Data to the extent necessary to comply with
        our legal obligations (for example, if we are required to retain your
        data to comply with applicable laws), resolve disputes, and enforce our
        legal agreements and policies.
      </Text>
      <Text>
        The Company will also retain Usage Data for internal analysis purposes.
        Usage Data is generally retained for a shorter period of time, except
        when this data is used to strengthen the security or to improve the
        functionality of Our Services, or We are legally obligated to retain
        this data for longer time periods.
      </Text>

      <Text tag="h3">Transfer of Your Personal Data</Text>
      <Text>
        Your information, including Personal Data, is processed at the Company's
        operating offices and in any other places where the parties involved in
        the processing are located. It means that this information may be
        transferred to — and maintained on — computers located outside of Your
        state, province, country or other governmental jurisdiction where the
        data protection laws may differ from those from Your jurisdiction.
      </Text>
      <Text>
        Your consent to this Privacy Policy followed by Your submission of such
        information represents Your agreement to that transfer.
      </Text>
      <Text>
        The Company will take all steps reasonably necessary to ensure that Your
        data is treated securely and in accordance with this Privacy Policy. Any
        transfer of data outside the EU/EEA is made in line with data protection
        laws. Our international transfers of Personal Data are based on the EU
        Commission&apos;s standard contractual clauses.
      </Text>

      <Text tag="h3">Your Rights</Text>
      <Text>
        You are entitled to the following rights under applicable data
        protections laws:
      </Text>
      <ul class="list-disc mb-8">
        <li>
          <Text noMargin>
            <b>The right to access:</b> You are entitled to receive certain
            information on our processing of Your Personal Data. Such
            information is provided in this information document. Further, You
            have the right to receive a copy of the Personal Data we process
            relating to You. Upon request, we will provide a copy of Your
            Personal Data in a commonly used electronic form.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>The right to rectification:</b> You are entitled to obtain
            rectification of inaccurate Personal Data and to have incomplete
            Personal Data completed.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>The right to erasure (“right to be forgotten”):</b> You may under
            certain circumstances request Us to delete Your Personal Data.
            Please note that this right is not unconditional. Therefore, an
            attempt to invoke the right might not lead to an action from Us.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>The right to restriction of processing:</b> You may under certain
            circumstances request from Us to restrict the processing of Your
            Personal Data. Please note that this right is not unconditional.
            Therefore, an attempt to invoke the right might not lead to an
            action from Us.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>The right to data portability:</b> You are entitled to receive
            Your Personal Data (or have Your Personal Data directly transmitted
            to another data controller) in a structured, commonly used and
            machine-readable format.
          </Text>
        </li>
        <li>
          <Text noMargin>
            <b>The right to object:</b> You are entitled to object to certain
            processing activities conducted by Us in relation to Your Personal
            Data, such as our processing of Your Personal Data based on Our
            legitimate interest.
          </Text>
        </li>
      </ul>
      <Text>
        You also have the right to lodge a complaint with
        Integritetsskyddsmyndigheten (IMY), the supervisory authority in Sweden.
      </Text>

      <Text tag="h3">Disclosure of Your Personal Data</Text>
      <Text tag="h4">Business Transactions</Text>
      <Text>
        If the Company is involved in a merger, acquisition or asset sale, Your
        Personal Data may be transferred. We will provide notice before Your
        Personal Data is transferred and becomes subject to a different Privacy
        Policy.
      </Text>
      <Text tag="h4">Law enforcement</Text>
      <Text>
        Under certain circumstances, the Company may be required to disclose
        Your Personal Data if required to do so by law or in response to valid
        requests by public authorities (e.g. a court or a government agency).
      </Text>
      <Text tag="h4">Other legal requirements</Text>
      <Text>
        The Company may disclose Your Personal Data in the good faith belief
        that such action is necessary to:
      </Text>
      <ul class="list-disc mb-8">
        <li>
          <Text noMargin>Comply with a legal obligation</Text>
        </li>
        <li>
          <Text noMargin>
            Protect and defend the rights or property of the Company
          </Text>
        </li>
        <li>
          <Text noMargin>
            Prevent or investigate possible wrongdoing in connection with the
            Services
          </Text>
        </li>
        <li>
          <Text noMargin>
            Protect the personal safety of Users of the Services or the public
          </Text>
        </li>
        <li>
          <Text noMargin>Protect against legal liability</Text>
        </li>
      </ul>

      <Text tag="h3">Security of Your Personal Data</Text>
      <Text>
        The security of Your Personal Data is important to Us, but remember that
        no method of transmission over the Internet, or method of electronic
        storage is 100% secure. While We strive to use commercially acceptable
        means to protect Your Personal Data, We cannot guarantee its absolute
        security.
      </Text>

      <Text tag="h2">Children's Privacy</Text>
      <Text>
        Our Services do not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13. If You are a parent or guardian and You are aware that
        Your child has provided Us with Personal Data, please contact Us. If We
        become aware that We have collected Personal Data from anyone under the
        age of 13 without verification of parental consent, We take steps to
        remove that information from Our servers.
      </Text>
      <Text>
        If We need to rely on consent as a legal basis for processing Your
        information and Your country requires consent from a parent, We may
        require Your parent's consent before We collect and use that
        information.
      </Text>

      <Text tag="h2">Links to Other Websites</Text>
      <Text>
        Our Services may contain links to other websites that are not operated
        by Us. If You click on a third party link, You will be directed to that
        third party's site. We strongly advise You to review the Privacy Policy
        of every site You visit.
      </Text>
      <Text>
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </Text>

      <Text tag="h2">Changes to this Privacy Policy</Text>
      <Text>
        We may update our Privacy Policy periodically to reflect changes in our
        privacy practices, laws, and best practices. We will post any changes we
        make to our Privacy Policy on this page. The date this Privacy Policy
        was last revised is identified at the top of the page. We recommend that
        you review the Privacy Policy each time you visit our Site to stay
        informed of our privacy practices.
      </Text>

      <Text tag="h2">Contact Us</Text>
      <Text>
        If you have any questions about this Privacy Policy or Our processing of
        Your Personal Data, You can contact us by using any of the two options
        below:
      </Text>
      <ul class="list-disc mb-8">
        <li>
          <Text noMargin>
            By visiting our website:{" "}
            <a href="https://untied.world">https://untied.world</a> to find
            contact information, or
          </Text>
        </li>
        <li>
          <Text noMargin>
            By writing to us at Untied World AB, Swedish registration number
            559400-2304, Bråvallagatan 8, 113 36 Stockholm Sweden.
          </Text>
        </li>
      </ul>
    </section>
  );
});

// sets the title and meta properties of the page
export const head: DocumentHead = {
  title: "Privacy policy - Untied",
  meta: [
    {
      name: "description",
      content:
        "This privacy policy has been compiled to better serve those who are concerned with how their 'Personally Identifiable Information' (PII) is being used online.",
    },
  ],
};
